In [1]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [2]:
# 定义数据
x = torch.randn(10, 3)
y = torch.randn(10)
print(x)
print(y)

tensor([[-0.6505,  0.9237, -1.9008],
        [-0.5051,  1.0923, -0.7623],
        [ 0.0129, -1.0447, -0.3011],
        [ 0.7206, -0.1588,  1.4674],
        [-0.8053, -0.1115,  0.5423],
        [-1.3515,  0.4654, -0.2609],
        [ 0.6510, -0.9186,  1.0442],
        [-0.6386,  0.2801, -0.5313],
        [ 0.3460,  1.0184,  0.3290],
        [-0.2765, -0.6837,  1.3208]])
tensor([ 0.9408, -0.5931, -0.3939,  0.4761, -1.7638, -1.0567, -0.9289,  1.3142,
        -1.2349, -0.3538])


In [3]:
# 构建数据集
dataset = TensorDataset(x, y)

In [15]:
# 定义加载器
dataloader = DataLoader(dataset, batch_size=4, shuffle=False, drop_last=True)

In [22]:
# 遍历每个批次的数据
for x, y in dataloader:
    print(x)
    print("y = ", y)
    print()

tensor([[-0.6505,  0.9237, -1.9008],
        [-0.5051,  1.0923, -0.7623],
        [ 0.0129, -1.0447, -0.3011],
        [ 0.7206, -0.1588,  1.4674]])
y =  tensor([ 0.9408, -0.5931, -0.3939,  0.4761])

tensor([[-0.8053, -0.1115,  0.5423],
        [-1.3515,  0.4654, -0.2609],
        [ 0.6510, -0.9186,  1.0442],
        [-0.6386,  0.2801, -0.5313]])
y =  tensor([-1.7638, -1.0567, -0.9289,  1.3142])

